// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mcShopServer.Context;

namespace mcShopServer.Migrations
{
    [DbContext(typeof(ShoppingContext))]
    [Migration("20190722103106_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("mcShopServer.Models.Item", b =>
                {
                    b.Property<long>("itemId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateOfCreation");

                    b.Property<long>("itemPrice");

                    b.Property<long>("itemQuantity");

                    b.Property<string>("mcItemId")
                        .IsRequired();

                    b.Property<string>("mcItemName")
                        .IsRequired();

                    b.Property<long>("userId");

                    b.HasKey("itemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("mcShopServer.Models.User", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("mcUserId")
                        .IsRequired();

                    b.Property<string>("mcUsername")
                        .IsRequired();

                    b.HasKey("userId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
